export const cityData = [
  "Yeola",
  "YavatmÄ l",
  "YÄ val",
  "WÄ shÄ«m",
  "Warud",
  "Warora",
  "Wardha",
  "Wani",
  "Wai",
  "Vite",
  "VirÄ r",
  "Vasind",
  "Varangaon",
  "VaijÄ pur",
  "VÄ da",
  "Uran",
  "Umred",
  "Umarkhed",
  "Umarga",
  "Ulhasnagar",
  "UdgÄ«r",
  "Tumsar",
  "TuljÄ pur",
  "ThÄ ne",
  "TelhÄ ra",
  "TÄ sgaon",
  "Taloda",
  "Talegaon DÄ bhÄ de",
  "SrÄ«vardhan",
  "Soygaon",
  "SirÅ«r",
  "Sinnar",
  "Sillod",
  "ShrÄ«gonda",
  "SolÄ pur",
  "Shirpur",
  "Shirdi",
  "Shegaon",
  "ShÄ hÄ da",
  "SÄ vda",
  "View from",
  "SÄ tÄ ra",
  "SatÄ nÄ ",
  "SÄ svad",
  "Saoner",
  "Sangola",
  "Sangli",
  "Sangamner",
  "Selu",
  "Roha",
  "Risod",
  "RÄ ver",
  "Ratnagiri",
  "RÄ mtek",
  "RÄ jÅ«ra",
  "RÄ jgurunagar",
  "RÄ houri",
  "Rahimatpur",
  "Pusad",
  "PÅ«rna",
  "Pune",
  "Pulgaon",
  "PÄ«pri",
  "Pimpri",
  "Phaltan",
  "Pen",
  "Pawni",
  "PÄ tÅ«r",
  "Patri",
  "PÄ thardi",
  "PartÅ«r",
  "Parola",
  "Parli VaijnÄ th",
  "Parbhani",
  "Panvel",
  "Pandharpur",
  "Pa lghar",
  "Paithan",
  "PÄ cries",
  "Osmanabad",
  "Ozar",
  "NipÄ ni",
  "Nilanga",
  "Neral",
  "Nashik",
  "Nandurbar",
  "NÄ ndÅ«ra Buzurg",
  "NÄ ndgaon",
  "Nanded",
  "Naldurg",
  "Nagpur",
  "MurtajÄ pur",
  "MurbÄ d",
  "MÅ«l",
  "Mukher",
  "Mudkhed",
  "Morsi",
  "Live",
  "MhÄ svÄ d",
  "Mehekar",
  "MÄ nwat",
  "ManmÄ d",
  "MÄ jalgaon",
  "MangrÅ«l PÄ«r",
  "MÄ lvan",
  "MalkÄ pur",
  "MÄ legaon",
  "MahÄ d",
  "Lonavla",
  "LonÄ r",
  "Latur",
  "KurduvÄ di",
  "KurandvÄ d",
  "Koynanagar",
  "Koregaon",
  "Kopargaon",
  "KolhÄ pur",
  "Kodoli",
  "Kinwat",
  "KhuldÄ bÄ d",
  "Khopoli",
  "Khetia",
  "Kharakvasla",
  "KhÄ pa",
  "KhÄ mgaon",
  "Khadki",
  "KÄ tol",
  "KarmÄ la",
  "Karjat",
  "Karanja",
  "KarÄ d",
  "Kannad",
  "Kankauli",
  "KÄ mthi",
  "KalyÄ n",
  "Kalmeshwar",
  "KalamnÅ«ri",
  "Kalamb",
  "KÄ gal",
  "Junnar",
  "JintÅ«r",
  "JÄ lna",
  "Jalgaon Jamod",
  "Jalgaon",
  "Jaisingpur",
  "India pur",
  "Igatpuri",
  "Ichalkaranji",
  "Hingoli",
  "HinganghÄ t",
  "HadgÄ on",
  "GondiÄ ",
  "Ghugus",
  "Ghoti Budrukh",
  "GhÄ tanji",
  "Gevrai",
  "GangÄ pur",
  "GangÄ kher",
  "Gadhinglaj",
  "Faizpur",
  "Erandol",
  "DurgÄ pur",
  "Dondaicha",
  "Dombivli",
  "Digras",
  "DÄ«glÅ«r",
  "DhÅ«lia",
  "DhÄ rÅ«r",
  "Dharma bÄ d",
  "Dharangaon",
  "DeÅ«lgaon RÄ ja",
  "Deoli",
  "DeolÄ li",
  "Daund",
  "DattÄ pur",
  "DaryÄ pur",
  "DÄ rwha",
  "DÄ hÄ nu",
  "Chopda",
  "ChiplÅ«n",
  "Chikhli",
  "Chicholi",
  "Chandor",
  "ChÄ ndÅ«r BÄ zÄ r",
  "ChÄ ndÅ«r",
  "Chandur",
  "ChÄ nda",
  "ChÄ lisgaon",
  "ChÄ kan",
  "BuldÄ na",
  "Borivli",
  "Mumbai",
  "Boisar",
  "BhusÄ val",
  "BhÅ«m",
  "Bhudgaon",
  "Bhor",
  "Bhiwandi",
  "Bhayandar",
  "BhandÄ ra",
  "Basmat",
  "BÄ rsi",
  "BÄ rÄ mati",
  "BallÄ lpur",
  "BÄ lÄ pur",
  "Badlapur",
  "Ausa",
  "Aurangabad",
  "Ashta",
  "Arvi",
  "Ä€rangaon",
  "Anshing",
  "Anjangaon",
  "AmrÄ vati",
  "AmbÄ jogÄ i",
  "Ambad",
  "Amarnath",
  "Amalner",
  "AlÄ«bÄ g",
  "Alandi",
  "Akot",
  "Akola",
  "Akalkot",
  "Ajra",
  "Ahmadpur",
  "Ahmadnagar",
  "Achalpur",
  "Powai",
  "Navi Mumbai",
  "Shivaji Nagar",
  "Airoli",
  "Shiraguppi",
];
